spring:
  data:
    mongodb:
      username: systemscheduling
      password: systemscheduling123
      host: localhost
      port: 27017
      database: dbsystemscheduling
      authentication-database: admin
      uri: mongodb+srv://systemscheduling:systemscheduling123@dbsystemscheduling.9se5shq.mongodb.net/?retryWrites=true&w=majority&tls=true&authMechanism=SCRAM-SHA-1&serverSelectionTimeoutMS=5000&serverTimezone=UTC
  # Mail settings
  # ?authMechanism=MONGODB-X509&tls=true&authSource=$external
  # ?retryWrites=true&w=majority
  mail:
    host: smtp.gmail.com
    port: 587
    username: systemscheduling281@gmail.com
    password: xgeyhknootvgmwtm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: sweetserenityweddingevent@gmail.com
#    password: gsdpdiqzvazdswuv
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true